import { StyleSheet } from 'react-native';
import theme from './theme'; // Certifique-se de que o caminho esteja correto

const styles = StyleSheet.create({
  container: {
    width: 360,
    height: 728,
    paddingTop: 21,
    paddingBottom: 357,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: theme.colors.background,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 17,
  },
  frame7: {
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  logo: {
    width: 30,
    height: 30,
  },
  user: {
    alignSelf: 'stretch',
    height: 303,
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 15,
    borderRadius: 10,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: 10,
  },
  frame3: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 10,
    flexDirection: 'row',
  },
  vector: {
    width: 34,
    height: 34,
  },
  editarFoto: {
    color: '#7A1AC4',
    fontSize: 12,
    fontFamily: 'Poppins',
    fontWeight: '600',
  },
  frame9: {
    width: 280,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: '#7A1AC4',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 10,
  },
  usuRio: {
    color: theme.colors.text,
    fontSize: 12,
    fontFamily: 'Poppins',
    fontWeight: '400',
  },
  frame10: {
    width: 280,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: '#7A1AC4',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 10,
  },
  eMail: {
    color: theme.colors.text,
    fontSize: 12,
    fontFamily: 'Poppins',
    fontWeight: '400',
  },
  frame11: {
    width: 280,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: '#7A1AC4',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 10,
  },
  regiO: {
    color: theme.colors.text,
    fontSize: 12,
    fontFamily: 'Poppins',
    fontWeight: '400',
  },
  frame8: {
    paddingLeft: 22,
    paddingRight: 22,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: theme.colors.primary,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  salvar: {
    color: 'white',
    fontSize: 12,
    fontFamily: 'Poppins',
    fontWeight: '600',
  },
  frame12: {
    width: 280,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deletarConta: {
    color: '#BA0000',
    fontSize: 12,
    fontFamily: 'Poppins',
    fontWeight: '600',
  },
  input: {
    width: '100%',
    height: 40,
    padding: 10,
    borderColor: '#7A1AC4',
    borderWidth: 1,
    borderRadius: 5,
    color: theme.colors.text,
    fontSize: 12,
    fontFamily: 'Poppins',
  },
});

export default styles;
